sae/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, include
from django.conf import settings
from django.contrib.auth import views as auth_views


from blog.views import HomePage, PostDetails, Categories, MiniCategories, RegistrationView, UserLogoutView, \
    AccountEmailActivate, UserPasswordResetComplete, SearchView, DataLiteracy
from accounts.forms import UserLoginForm, UserPasswordResetForm, UserPasswordResetConfirmForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', HomePage.as_view(), name='data-literacy-project'),

    path('', DataLiteracy.as_view(), name='home'),
    path('home/', include('datalab.urls'), name='home-auth-redirect'),

    path('posts/<slug:post_slug>/', PostDetails.as_view(), name='post-details'),
    path('categories/<slug:post_slug>', Categories.as_view(), name='categories'),
    path('mini/<slug:post_slug>', MiniCategories.as_view(), name='mini-categories'),

    path('ajax/search/', SearchView.as_view(), name='search-view'),

    path('data-literacy/', DataLiteracy.as_view(), name='data-literacy-project'),

    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True,
         template_name='blog/login.html',
         authentication_form=UserLoginForm), name='user-login'),
    path('register/', RegistrationView.as_view(), name='user-register'),

    path('logout/',
         login_required(UserLogoutView.as_view(template_name='blog/index.html', )),
         {'next_page': settings.LOGOUT_REDIRECT_URL}, name='user-logout'),


    re_path(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$',
                AccountEmailActivate.as_view(),
                name='email-activate'),

    path('reset/',
         auth_views.PasswordResetView.as_view(
             template_name='blog/password_reset_form.html',
             form_class=UserPasswordResetForm,
         ),

         name='password-reset'),
    path('reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='blog/password_reset_done.html'
         ),
         name='password_reset_done'),


    path('reset/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='blog/password_reset_confirm.html',
             form_class=UserPasswordResetConfirmForm,

         ),
         name='password_reset_confirm'),
    path('reset/complete/',
         UserPasswordResetComplete.as_view(
             template_name='blog/password_reset_complete.html',
         ),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from datetime import timedelta

from django.conf import settings
from django.db import models
from django.db.models import Prefetch
from django.utils import timezone

from blog.abstractModels import TimeStampModel
from django.contrib.auth import get_user_model
from django.utils.text import slugify


User = get_user_model()

DEFAULT_FEATURE_DAYS = getattr(settings, 'DEFAULT_FEATURE_DAYS', 7)


class Tags(TimeStampModel):

    name = models.CharField(max_length=100, unique=True)
    slug_name = models.SlugField(max_length=100, unique=True, blank=True)

    class Meta:
        verbose_name = 'post tag'
        verbose_name_plural = 'post tags'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.name)
        super(Tags, self).save(*args, **kwargs)


class BlogCategoryManager(models.Manager):
    def active(self):
        return self.get_queryset().filter(is_active=True).prefetch_related('postcategory_set')

    def per_category(self, filter_value):
        return self.prefetch_related(
            Prefetch(
                'postcategory_set',
                queryset=PostCategory.objects.prefetch_related(
                    Prefetch(
                        'post_set',
                        queryset=Post.objects.prefetch_related(
                            'has_tags'
                        )
                    )
                ))
        ).get(slug_name=filter_value)


class BlogCategory(TimeStampModel):

    name = models.CharField(max_length=100, verbose_name='Blog Categories')

    slug_name = models.SlugField(max_length=100, unique=True, blank=True)

    objects = BlogCategoryManager()

    class Meta:
        verbose_name = 'Main Blog Category'
        verbose_name_plural = 'Main Blog categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.name)
        super(BlogCategory, self).save(*args, **kwargs)


class SiteCategoryManager(models.Manager):
    def active(self):
        return self.get_queryset().filter(is_active=True)


class SiteCategory(TimeStampModel):

    name = models.CharField(max_length=100, verbose_name='Website Categories')

    slug_name = models.SlugField(max_length=100, unique=True, blank=True)

    objects = SiteCategoryManager()

    class Meta:
        verbose_name = 'Website Navigation Category'
        verbose_name_plural = 'Website Navigation Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.name)
        super(SiteCategory, self).save(*args, **kwargs)


class Comment(TimeStampModel):
    comment = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.comment[10]


class PostCategory(TimeStampModel):
    belongs_to = models.ForeignKey(BlogCategory, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=255)
    slug_name = models.SlugField(unique=True, blank=True)

    class Meta:
        verbose_name = 'Post Category'
        verbose_name_plural = 'Posts categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.name)
        super(PostCategory, self).save(*args, **kwargs)


def image_upload_path(instance, file_name):
    return '{}/{}/{}'.format(instance.created_on, instance.created_by, file_name)


class PostQuerySet(models.QuerySet):
    def featured_post(self, flags):
        now = timezone.now()
        start_range = now - timedelta(days=DEFAULT_FEATURE_DAYS)
        end_range = now
        return self.filter(
            is_active=True,
            flags=flags,
        ).filter(
            created_on__gt=start_range,
            created_on__lte=end_range,
        )


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def featured_post(self, flags):
        return self.get_queryset().featured_post(flags)


class Post(TimeStampModel):
    has_tags = models.ManyToManyField(Tags)
    belongs_to = models.ForeignKey(PostCategory, on_delete=models.DO_NOTHING, blank=True, null=True)
    hard_title = models.CharField(max_length=1000)
    soft_title = models.CharField(max_length=1000)
    title_image = models.ImageField(upload_to=image_upload_path)
    post_body_first = models.TextField()
    post_body_second = models.TextField(blank=True, null=True)
    highlight_content = models.TextField(blank=True, null=True)
    view_count = models.PositiveIntegerField(default=0)
    comments = models.ManyToManyField(Comment, blank=True)
    flags = models.PositiveIntegerField(blank=True, null=True)
    # flag:1-3 - featured  flag:5-10 - picks
    slug_name = models.SlugField(max_length=1000, unique=True, blank=True)

    objects = PostManager()

    class Meta:
        verbose_name = 'Blog Post '
        verbose_name_plural = 'Blog Posts'

    def __str__(self):
        return self.hard_title

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.hard_title)
        super(Post, self).save(*args, **kwargs)


def subpostcontentimage(instance,file_name):
    return '{}/{}/{}'.format(instance.created_on, instance.created_by, file_name)


class SubPostContent(TimeStampModel):
    belongs_to = models.ForeignKey(Post, on_delete=models.CASCADE,)
    inter_post_sequence = models.PositiveIntegerField(default=1)
    inter_post_heading = models.CharField(max_length=200)
    inter_post_content_one = models.TextField()
    inter_post_content_one_url = models.URLField(max_length=1000, null=True, blank=True)

    inter_post_content_two = models.TextField(blank=True, null=True)
    inter_post_content_two_url = models.URLField(max_length=1000, null=True, blank=True)
    inter_post_content_three = models.TextField(blank=True, null=True)
    inter_post_content_three_url = models.URLField(max_length=1000, null=True, blank=True)

    highlight_content = models.TextField(blank=True, null=True)
    post_image = models.ImageField(upload_to=subpostcontentimage, blank=True, null=True)

    class Meta:
        verbose_name = 'Blog Post Heading '
        verbose_name_plural = 'Blog Posts Headings'
        ordering = ['inter_post_sequence']

    def __str__(self):
        return self.inter_post_heading


class SubPostListElements(TimeStampModel):
    belongs_to = models.ForeignKey(SubPostContent, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000, null=True, blank=True)
    title_url = models.URLField(max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = 'Sub Post List Element'
        verbose_name_plural = 'Sub Post List Elements'

    def __str__(self):
        return self.title


class ListElements(TimeStampModel):
    belongs_to = models.ForeignKey(SubPostListElements, on_delete=models.CASCADE)
    element = models.CharField(max_length=1000)
    element_url = models.URLField(max_length=1000, null=True, blank=True)

    class Meta:
        verbose_name = 'List Element '
        verbose_name_plural = 'List Elements'

    def __str__(self):
        return self.element

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}
{% load static %}


{% block title %}
    {{ whereiam|upper }}{{ block.super }}

{% endblock %}


{% block body %}
{#    <div class="secondary-nav">#}
{#        <ul class="secondary-nav">#}
{#        {% if active_category.postcategory_set.all %}#}
{#            {% for navheading in active_category.postcategory_set.all  %}#}
{#                <li><a href="{% url 'mini-categories' navheading.slug_name %}">{{ navheading }}</a></li>#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#        </ul>#}
{#    </div>#}
        {# END SECONDARY NAV #}

    <div class="category-distance">
{#            <div class="whereiam-wrapper">#}
{#                <a href="{% url 'home' %}">HOME</a> > <a href="">{{ whereiam |upper }} ></a>#}
{#            </div>#}


             <div class="banner">
                <div class="left-banner">
                    <div class="img-wrap-lb">
                        <a href="#"><img src="{{ the_featured_one.title_image.url }}" alt=""></a>
                    </div>

                    <div class="title-wrap-lb">
                        <p class="belongs_to">{{ the_featured_one.belongs_to }}</p>
                        <a href="{% url 'post-details' the_featured_one.slug_name %}"><h1>{{ the_featured_one.hard_title }}</h1></a>

                        <p class="title-detail">
                            {{ the_featured_one.soft_title }}
                        </p>
                        <div class="timeofpost">
                            <div>
                                a few hours ago | 4 mins read
                            </div>
                            <div class="post-icons">
                                <i class="fas fa-ellipsis-h"></i>
                                <i class="far fa-bookmark"></i>

                            </div>
                        </div>
                    </div>
{#                  end left banner   #}

                </div>
             <div class="middle-banner-category only-mobile">
                    {% for featured in blog_categories %}
                        <div class="first-mb">
                            <div class="content-wrapper-mb">
                                <p class="belongs_to">{{ featured.belongs_to }}</p>
                                <a href="{% url 'post-details' featured.slug_name %}"><h2>{{ featured.hard_title }}</h2></a>
                                 <div class="img-wrapper-mb">
                                      <a href="{% url 'post-details' featured.slug_name %}"><img src="{{ featured.title_image.url }}" alt="STONEAGEENTREPRENEUR"></a>

                                </div>
                                <p class="title-detail">
                                   {{ featured.soft_title }}
                                </p>
                                <div class="timeofpost">
                                    <div>
                                        a few hours ago | 4 mins read
                                    </div>
                                    <div class="post-icons">
                                        <i class="fas fa-ellipsis-h"></i>
                                        <i class="far fa-bookmark"></i>

                                    </div>
                                </div>
                            </div>




                        </div>


                    {% endfor %}
{#                #}

                </div>
                <div class="middle-banner-category except-mobile">
                    {% for featured in blog_categories %}
                        <div class="first-mb">
                            <div class="content-wrapper-mb">
                                <p class="belongs_to">{{ featured.belongs_to }}</p>
                                <a href="{% url 'post-details' featured.slug_name %}"><h2>{{ featured.hard_title }}</h2></a>
                                <p class="title-detail">
                                   {{ featured.soft_title }}
                                </p>
                                <div class="timeofpost">
                                    <div>
                                        a few hours ago | 4 mins read
                                    </div>
                                    <div class="post-icons">
                                        <i class="fas fa-ellipsis-h"></i>
                                        <i class="far fa-bookmark"></i>

                                    </div>
                                </div>
                            </div>

                            <div class="img-wrapper-mb">
                                <a href="{% url 'post-details' featured.slug_name %}"><img src="{{ featured.title_image.url }}" alt="STONEAGEENTREPRENEUR"></a>

                            </div>


                        </div>


                    {% endfor %}
{#                #}

                </div>
{#        #end middle  banner#}

            </div>
{#            END BANNER                    #}
    </div>

{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}

{% endblock %}


{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}
    <h1> Welcome to Stone Age Entrepreneur</h1>
    {{ request.user }}
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block title %}

{% endblock %}



{% block body %}



{% endblock %}

blog/templates/blog/minicategories.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ whereiam|upper }}{{ block.super }}
{% endblock %}

{% block secondary-nav %}

{% endblock %}
{% block body %}

    <div class="category-distance">
{#            <div class="whereiam-wrapper-mini">#}
{#                <a href="{% url 'home' %}"> HOME  </a> > <a href="{% url 'categories' whereiwas.slug_name %}">{{ whereiwas |upper }}</a> <span> ></span>   <a href="#">{{ whereiam |upper }}</a>#}
{#            </div>#}
            <div class="middle-banner except-mobile">
                {% for featured in posts %}
                    <div class="first-mb">
                        <div class="content-wrapper-mb">
                            <p class="belongs_to">{{ featured.belongs_to }}</p>
                            <a href="{% url 'post-details' featured.slug_name %}"><h2>{{ featured.hard_title }}</h2></a>
                            <p class="title-detail">
                               {{ featured.soft_title }}
                            </p>
                            <div class="timeofpost">
                                <div>
                                    a few hours ago | 4 mins read
                                </div>
                                <div class="post-icons">
                                    <i class="fas fa-ellipsis-h"></i>
                                    <i class="far fa-bookmark"></i>

                                </div>
                            </div>
                        </div>

                        <div class="img-wrapper-mb">
                            <a href="{% url 'post-details' featured.slug_name %}"><img src="{{ featured.title_image.url }}" alt="STONEAGEENTREPRENEUR"></a>

                        </div>


                    </div>


                {% endfor %}

         </div>
        <div class="middle-banner only-mobile">
                {% for featured in posts %}
                    <div class="first-mb">
                        <div class="content-wrapper-mb">
                            <p class="belongs_to">{{ featured.belongs_to }}</p>
                            <a href="{% url 'post-details' featured.slug_name %}"><h2>{{ featured.hard_title }}</h2></a>
                            <div class="img-wrapper-mb">
                              <a href="{% url 'post-details' featured.slug_name %}"><img src="{{ featured.title_image.url }}" alt="STONEAGEENTREPRENEUR"></a>

                            </div>
                            <p class="title-detail">
                               {{ featured.soft_title }}
                            </p>
                            <div class="timeofpost">
                                <div>
                                    a few hours ago | 4 mins read
                                </div>
                                <div class="post-icons">
                                    <i class="fas fa-ellipsis-h"></i>
                                    <i class="far fa-bookmark"></i>

                                </div>
                            </div>
                        </div>




                    </div>


                {% endfor %}

         </div>
    </div>


{% endblock %}

blog/templates/blog/password_reset_complete.html
{% extends 'blog/base.html' %}


{% block title %}

{% endblock %}

{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}

 <div class="login-modal-individual " id="loginModal">

            <div class="login-wrapper">
                <div class="login-wrapper-login">

                     <div class="logo-reset">
                        <a  href="{% url 'home' %}">Stone<span>Age</span>Entrepreneur.</a>

                    </div>
{#                <span class="sign-in"><p>Password Reset Complete</p></span>#}

                     <span class="sign-in">SIGN IN</span>
                <div class="success-message">
                  {% if messages %}
                        {% for message in messages %}
                            {% if color %}
                                <div style="margin-top: 20px; color: red;">

                                        {{ message }}

                                </div>
                            {% else %}
                                <div style="margin-top: 20px; color: green;">

                                    {{ message }}

                                </div>
                            {% endif %}


                        {% endfor %}

                  {% endif %}
                </div>


                <form id="login-form" class="login-form-control"  method="post">
                    {% csrf_token %}
                    {{ form }}


                    <div class="reset-forget-wrapper">
                        <a class="register-link" href="{% url 'user-register' %}">Register?</a>
                        <a href="{% url 'password-reset' %}">Forget Password?</a>
                    </div>
                      {{ login_url }}
                    <button class="login-submit" type="submit">Sign in</button>
                </form>

                <div class="social-link-wrapper">
                    <p>Or sign in with</p>
                    <div class="social-facebook">
                        <a href="#">
                            <i class="fab fa-google"></i>
                            <p>Sign in with Google</p>
                        </a>
                    </div>
                     <div class="social-facebook">
                        <a href="#">
                            <i class="fab fa-facebook"></i>
                            <p>Sign in with Facebook</p>
                        </a>
                    </div>
                </div>
            </div>

            <div class="termscond">
                <small>Click “Sign In” above to accept Stone Age Entrepreneur's</small>
                    <small>Terms of Service & Privacy Policy.</small>

            </div>
            </div>




            </div>

 </div>
{% endblock %}


{% block footer %}

{% endblock %}

blog/templates/blog/password_reset_confirm.html
{% extends 'blog/base.html' %}


{% block title %}

{% endblock %}

{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}

 <div class="login-modal-individual " id="loginModal">

            <div class="login-wrapper">
                <div class="login-wrapper-login">
                    <div class="logo-reset">
                        <a  href="{% url 'home' %}">Stone<span>Age</span>Entrepreneur.</a>

                    </div>
                <span class="sign-in-reset"><p>Enter Your New Password</p></span>

                <form id="login-form" class="login-form-control"  method="post">
                    {% csrf_token %}
                    {{ form }}




                    <button class="login-submit" type="submit">Submit</button>
                </form>


            </div>

 </div>
{% endblock %}


{% block footer %}

{% endblock %}

blog/templates/blog/password_reset_done.html
{% extends 'blog/base.html' %}


{% block title %}

{% endblock %}

{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}

 <div class="login-modal-individual " id="loginModal">
<div class="login-wrapper">
                <div class="login-wrapper-login">
                     <div class="logo-reset">
                        <a  href="{% url 'home' %}">Stone<span>Age</span>Entrepreneur.</a>

                    </div>



                    <span class="sign-in-reset">
                                            <p>A password reset link has be sent to your Email Address.</p>


                        <p>Please check your Email.</p>

                        <p><a href="{% url 'home' %}">Click <span style="color: green">HERE</span> to be redirected to the HomePage.</a> </p>
                        </span>








            </div>
 </div>
{% endblock %}


{% block footer %}

{% endblock %}

blog/templates/blog/password_reset_form.html
{% extends 'blog/base.html' %}


{% block title %}

{% endblock %}

{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}

 <div class="login-modal-individual " id="loginModal">

            <div class="login-wrapper">
                <div class="login-wrapper-login">
                     <div class="logo-reset">
                        <a  href="{% url 'home' %}">Stone<span>Age</span>Entrepreneur.</a>

                    </div>



                    <span class="sign-in-reset"><p>Enter Your Email to Reset Your Password</p>
                    <p>A password reset link will be sent to your Email Address.</p>
                        </span>

                    <form id="login-form" class="login-form-control"  method="post">
                        {% csrf_token %}
                        {{ form }}




                        <button class="login-submit" type="submit">Submit</button>
                    </form>





            </div>

 </div>
{% endblock %}


{% block footer %}

{% endblock %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}
    {{ title }} {{ block.super }}
{% endblock %}


{% block body %}



        <div class="post-content">

             <div class="title-post-content">
                <h1>{{ post.hard_title }}</h1>
             </div>

            <div class="user-details-mobile only-mobile">
                <div class="user-details">
                    <p>Ayurma Wagle</p>
                    <p>{{ post.created_on }} </p>


                </div>
            </div>

             <div class="post-image-wrapper">
                <img src="{{ post.title_image.url }}" alt="">
             </div>


        <div class="user-details-mobile only-mobile">
            <div class="icons">
                    <i class="fas fa-book-reader"></i>
                <span class="reads">{{ post.view_count }} Reads</span>
                    <i class="fas fa-bookmark"></i>
                <span>10 Bookmarks</span>
                    <i class="fas fa-share-alt"></i>
                <span>5 Shares</span>
            </div>
        </div>



        </div>
        <div class="post-content-text">
            {% if post.post_body_first %}

                <p>{{ post.post_body_first|safe|linebreaks }}</p>
            {% endif %}
            {% if post.highlight_content != '' %}
                <div class="highlight">
                    <p>
                        {{ post.highlight_content }}
                    </p>
                </div>
            {% endif %}
            {% if post.post_body_second %}
                <p>{{ post.post_body_second|linebreaksbr }}</p>
            {% endif %}

{#        End if post title main #}
            {% if post.subpostcontent_set.all %}
                {% for related in post.subpostcontent_set.all %}

                    <h2>{{ related.inter_post_heading }}</h2>
                    {% if related.inter_post_content_one %}
                       <p>
                           {{ related.inter_post_content_one|linebreaks }}
                       </p>
                        {% if related.inter_post_content_one_url %}
                            <p>
                               <script src="{{ related.inter_post_content_one_url }}"></script>
                            </p>

                        {% endif %}

                    {% endif %}
                    <div class="list-elements">
                    {% if related.subpostlistelements_set.all %}
                        {% for subpostlistelement in related.subpostlistelements_set.all  %}
                            <div class="list-title">
                                <p>
                                    {{ forloop.counter }}. {{subpostlistelement.title }}
                                    <script src="{{ subpostlistelement.title_url }}"></script>
                                </p></div>
                            {% for listelement in subpostlistelement.listelements_set.all %}

                               <div class="list-content">
                                   <ul>
                                       <li>{{ listelement.element }}</li>
                                       {% if listelement.element_url %}
                                           <div class="embed-code">
                                               <script src="{{ listelement.element_url}}"></script>
                                           </div>

                                       {% endif %}
                                   </ul>
                               </div>
                            {% endfor %}

                        {% endfor %}


                    {% endif %}
                    </div>


                   {% if related.inter_post_content_two %}
                       <p>
                           {{ related.inter_post_content_two|linebreaks }}
                       </p>
                        {% if related.inter_post_content_two_url %}
                            <p>
                               <script src="{{ related.inter_post_content_two_url }}"></script>
                            </p>

                        {% endif %}

                    {% endif %}

                    {% if related.inter_post_content_three %}
                       <p>
                           {{ related.inter_post_content_three|linebreaks }}
                       </p>
                        {% if related.inter_post_content_three_url %}
                            <p>
                               <script src="{{ related.inter_post_content_three_url }}"></script>
                            </p>

                        {% endif %}

                    {% endif %}

                    {% if related.highlight_content != '' %}
                        <div class="highlight">
                        <p>
                            {{ related.highlight_content }}
                        </p>
                        </div>
                    {% endif %}


                    {% if related.post_image != '' %}
                        <div class="post-image-wrapper ">
                            <img src="{{ related.post_image.url }}" alt="">
                        </div>

                    {% endif %}



                {% endfor %}
            {% endif %}

        </div>
        <div class="floating-reaction-wrapper except-mobile">
            <div class="floating-reaction">
                <div class="user-details">
                    <img src="{% static 'blog/img/profileimg.png' %}" alt="">
                    <p>Ayurma Wagle</p>
                    <p>{{ post.created_on }} </p>


                </div>
                <hr class="hrline">


                <i class="fas fa-book-reader"></i><span class="reads">{{ post.view_count }} Reads</span>
                <i class="fas fa-bookmark"></i><span>10 Bookmarks</span>


                <i class="fas fa-share-alt"></i><span>5 Shares</span>






            </div>
        </div>





{% endblock %}

blog/templates/blog/registration-error.html
{% extends 'blog/base.html' %}


{% block title %}

{% endblock %}

{% block navigation %}

{% endblock %}

{% block secondary-nav %}

{% endblock %}

{% block body %}

 <div class="login-modal-individual " id="loginModal">

            <div class="login-wrapper">
                <div class="login-wrapper-login">



{#                <span class="sign-in">Enter Your Email to Reset Your Password</span>#}

                    <h4 class="sign-in">You have either forgot to activate your account or an error has occurred !!!</h4>

                <h5 class="sign-in">Do you want us to resend a verification Link?</h5>

                <form id="login-form" class="login-form-control"  method="post">
                    {% csrf_token %}
                    {{ form }}




                    <button class="login-submit" type="submit">Submit</button>
                </form>


            </div>

 </div>
{% endblock %}


{% block footer %}

{% endblock %}